### ISSUE TITLE
Global Search: Display relevant Alternate Title

### ISSUE THREAD

**Issue by kbeelman** [kbeelman/TokuCinema#13]
If a search result is shown due to the query matching a movie's specific Alternate Title, then display that Alternate Title. If the search result wasn't triggered by an Alternate Title, default to whatever is the first Alternate Title.

Examples:
- User searches for "Smog Monster". The results show "Godzilla vs. Hedorah (1971), _Godzilla vs. The Smog Monster_"
- User searches for "The Thing". The results show "Mothra vs. Godzilla (1964), _Godzilla vs. The Thing_"

**Comment by bayes343** [comment]
Makes sense.  It'll be a little complex since the 'search' is more of a 'filter' than a 'query.'  I'm sure I can make it happen though.

**Comment by kbeelman** [comment]
[http://i.imgur.com/CsCmllk.png](http://i.imgur.com/CsCmllk.png)

**Comment by bayes343** [comment]
This actually was pretty easy.

**Comment by bayes343** [comment]
Here's the one caveat - display names aren't going to be re-generated once the tab is drawn.  So if you type 1954 Godzilla, King.  The alt title isn't going to be Godzilla, King of the Monsters, because the display name was already generated by the "1954" piece.  Searching for "Godzilla, King...", "The Thing...", "Smog Monster", etc. will have the desired result though.
